#!/usr/bin/env bash 
#install nginx
#should listen on port 80
#configure port 80

sudo apt-get update -y -qq
sudo apt-get install nginx -y

#starting nginx service
sudo service nginx start

#allowing nginx on firewall
sudo ufw allow "Nginx HTTP"

#give ownership of files
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo -e "Holberton School!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Restarting nginx
sudo service nginx restart
