#!/usr/bin/env bash 
#install nginx
#should listen on port 80
#configure port 80

sudo apt-get update -y -qq
sudo apt-get install nginx -y

#starting nginx service
sudo service nginx start

#allowing nginx on firewall
sudo ufw allow "Nginx HTTP"

#give ownership of files
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo -e "Ceci n'est pas une page" | dd status=none of=/var/www/html/index.nginx-debian.html

# Setting up /redirect_me to a youtube video
sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Set up a 404 page
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default

# Restarting nginx
sudo service nginx restart
